/*	
 *	buildConfig.h -- Build configuration file.
 *	
 *	WARNING: DO NOT EDIT. This file is generated by configure.
 *
 *	Use "./configure --help" to learn how to use the configure script to 
 *	customize the configuration. 
 */	

 #ifdef BLD_ALTERNATE_CONFIG
 #include BLD_ALTERNATE_CONFIG
 #else
#define BLD_PRODUCT "appweb"
#define BLD_NAME "Embedthis Appweb"
#define BLD_VERSION "2.4.4"
#define BLD_NUMBER "0"
#define BLD_TYPE "DEBUG"
#define BLD_DEFAULTS "standard"
#define BLD_PACKAGES ""
#define BLD_MBEDTHIS 1
#define BLD_REQUIRED_TOOLS "AR CC CXX LD LDXX"
#define BLD_OPTIONAL_TOOLS ""
#define BLD_REQUIRED_SDKS ""
#define BLD_OPTIONAL_SDKS ""
#define BLD_REQUIRED_BUILD_TOOLS "AR CC CXX LD LDXX"
#define BLD_OPTIONAL_BUILD_TOOLS "DOXYGEN PKG"
#define BLD_REQUIRED_BUILD_SDKS ""
#define BLD_OPTIONAL_BUILD_SDKS ""
#define BLD_COMPANY "Embedthis"
#define BLD_DEBUG 1
#define BLD_DIRS "tools include obj lib bin mpr ejs esp http doc appweb samples package releases"
#define BLD_CLEAN_INSTALL "0"
#define BLD_LICENSE "gpl"
#define BLD_COMMERCIAL "0"
#define BLD_HOST_SYSTEM "i386-apple-macosx"
#define BLD_BUILD_SYSTEM "i386-apple-macosx"
#define BLD_CROSS "0"
#define BLD_HOST_OS "MACOSX"
#define BLD_HOST_CPU_ARCH MPR_CPU_IX86
#define BLD_HOST_CPU "i386"
#define BLD_HOST_CPU_UPPER "I386"
#define BLD_HOST_CPU_MODEL "386"
#define BLD_HOST_DIST "Mac"
#define BLD_HOST_DIST_VER "10.11.6"
#define BLD_HOST_UNIX 1
#define BLD_HOST_WIN 0
#define BLD_BUILD_OS "MACOSX"
#define BLD_BUILD_CPU_ARCH MPR_CPU_IX86
#define BLD_BUILD_CPU i386
#define BLD_BUILD_CPU_UPPER I386
#define BLD_BUILD_CPU_MODEL 386
#define BLD_BUILD_UNIX 1
#define BLD_BUILD_WIN 0
#define BLD_ROOT_PREFIX "/"
#define BLD_PREFIX "/Applications/Embedthis Appweb.app/Contents"
#define BLD_DOC_PREFIX "/Applications/Embedthis Appweb.app/Contents/Resources/doc"
#define BLD_INC_PREFIX "/usr/include/appweb"
#define BLD_LIB_PREFIX "/usr/lib/appweb"
#define BLD_LOG_PREFIX "/var/log/appweb"
#define BLD_MAN_PREFIX "/usr/share/man/man1"
#define BLD_SAM_PREFIX "/Applications/Embedthis Appweb.app/Contents/samples"
#define BLD_SBIN_PREFIX "/Applications/Embedthis Appweb.app/Contents/MacOS"
#define BLD_SRC_PREFIX "/Applications/Embedthis Appweb.app/Contents/src"
#define BLD_HOST_CC_MTUNE 1
#define BLD_HOST_CC_STACK_PROTECTOR 1
#define BLD_HOST_CC_MSCL 0
#define BLD_HOST_CC_CL_VERSION 
#define BLD_BUILD_CC_MTUNE 1
#define BLD_BUILD_CC_STACK_PROTECTOR 1
#define BLD_BUILD_CC_MSCL 0
#define BLD_BUILD_CC_CL_VERSION 
#define BLD_MOD_PREFIX "/usr/lib/appweb/modules"
#define BLD_WEB_PREFIX "/Library/Appweb"
#define BLD_APPWEB 1
#define BLD_HTTP_PORT 7777
#define BLD_SSL_PORT 4443
#define BLD_APPWEB_CONFIG "standard.conf"
#define BLD_FEATURE_ACCESS_LOG 1
#define BLD_FEATURE_ADMIN_MODULE 1
#define BLD_FEATURE_ASPNET_MODULE 0
#define BLD_FEATURE_ASSERT 0
#define BLD_FEATURE_AUTH_MODULE 1
#define BLD_FEATURE_C_API_MODULE 1
#define BLD_FEATURE_C_API_CLIENT 1
#define BLD_FEATURE_CGI_MODULE 1
#define BLD_FEATURE_DIR_MODULE 1
#define BLD_FEATURE_DOC 0
#define BLD_FEATURE_CMD_EXEC 1
#define BLD_FEATURE_GACOMPAT_MODULE 0
#define BLD_FEATURE_CONFIG_PARSE 1
#define BLD_FEATURE_CONFIG_SAVE 0
#define BLD_FEATURE_COOKIE 1
#define BLD_FEATURE_COPY_MODULE 1
#define BLD_FEATURE_DIGEST 1
#define BLD_FEATURE_EGI_MODULE 1
#define BLD_FEATURE_EJS 1
#define BLD_FEATURE_ESP_MODULE 1
#define BLD_FEATURE_EVAL_PERIOD 30
#define BLD_FEATURE_FLOATING_POINT 1
#define BLD_FEATURE_IF_MODIFIED 1
#define BLD_FEATURE_IPV6 0
#define BLD_FEATURE_KEEP_ALIVE 1
#define BLD_FEATURE_LEGACY_API 0
#define BLD_FEATURE_LICENSE 0
#define BLD_FEATURE_LOG 1
#define BLD_FEATURE_DLL 1
#define BLD_FEATURE_MULTITHREAD 1
#define BLD_FEATURE_NUM_TYPE int
#define BLD_FEATURE_NUM_TYPE_ID MPR_TYPE_INT
#define BLD_FEATURE_STDCPP 0
#define BLD_FEATURE_PUT_MODULE 1
#define BLD_FEATURE_RANGES 1
#define BLD_FEATURE_ROMFS 0
#define BLD_FEATURE_RUN_AS_SERVICE 1
#define BLD_FEATURE_SAFE_STRINGS 0
#define BLD_FEATURE_SAMPLES 1
#define BLD_FEATURE_SESSION 1
#define BLD_FEATURE_SHARED 1
#define BLD_FEATURE_SQUEEZE 0
#define BLD_FEATURE_SSL_MODULE 1
#define BLD_FEATURE_STATIC 1
#define BLD_FEATURE_STATIC_LINK_LIBC 0
#define BLD_FEATURE_TEST 0
#define BLD_FEATURE_UPLOAD_MODULE 1
#define BLD_FEATURE_SERVICES 1
#define BLD_FEATURE_ADMIN_MODULE_BUILTIN 0
#define BLD_FEATURE_ASPNET_MODULE_BUILTIN 0
#define BLD_FEATURE_AUTH_MODULE_BUILTIN 0
#define BLD_FEATURE_C_API_MODULE_BUILTIN 0
#define BLD_FEATURE_CGI_MODULE_BUILTIN 0
#define BLD_FEATURE_DIR_MODULE_BUILTIN 0
#define BLD_FEATURE_GACOMPAT_MODULE_BUILTIN 0
#define BLD_FEATURE_COPY_MODULE_BUILTIN 0
#define BLD_FEATURE_EGI_MODULE_BUILTIN 0
#define BLD_FEATURE_ESP_MODULE_BUILTIN 0
#define BLD_FEATURE_SSL_MODULE_BUILTIN 0
#define BLD_FEATURE_PUT_MODULE_BUILTIN 0
#define BLD_FEATURE_UPLOAD_MODULE_BUILTIN 0
#define BLD_FEATURE_ADMIN_MODULE_LOADABLE 1
#define BLD_FEATURE_ASPNET_MODULE_LOADABLE 0
#define BLD_FEATURE_AUTH_MODULE_LOADABLE 1
#define BLD_FEATURE_C_API_MODULE_LOADABLE 1
#define BLD_FEATURE_CGI_MODULE_LOADABLE 1
#define BLD_FEATURE_DIR_MODULE_LOADABLE 1
#define BLD_FEATURE_GACOMPAT_MODULE_LOADABLE 0
#define BLD_FEATURE_COPY_MODULE_LOADABLE 1
#define BLD_FEATURE_EGI_MODULE_LOADABLE 1
#define BLD_FEATURE_ESP_MODULE_LOADABLE 1
#define BLD_FEATURE_SSL_MODULE_LOADABLE 1
#define BLD_FEATURE_PUT_MODULE_LOADABLE 1
#define BLD_FEATURE_UPLOAD_MODULE_LOADABLE 1
#define BLD_MOD_DIR "${BLD_TOP}/lib/modules"
#define BLD_HOST_AR "/usr/bin/ar"
#define BLD_HOST_CC "/usr/bin/cc"
#define BLD_HOST_CXX "/usr/bin/g++"
#define BLD_HOST_LD "/usr/bin/cc"
#define BLD_HOST_LDXX "/usr/bin/g++"
#define BLD_BUILD_AR "/usr/bin/ar"
#define BLD_BUILD_CC "/usr/bin/cc"
#define BLD_BUILD_CXX "/usr/bin/g++"
#define BLD_BUILD_LD "/usr/bin/cc"
#define BLD_BUILD_LDXX "/usr/bin/g++"
#define BLD_BUILD_DOXYGEN "/usr/local/bin/doxygen"
#define BLD_BUILD_PKG ""
#define BLD_BUILD_CFLAGS ""
#define BLD_HOST_CFLAGS ""
#define BLD_BUILD_CXXFLAGS ""
#define BLD_HOST_CXXFLAGS ""
#define BLD_BUILD_IFLAGS ""
#define BLD_HOST_IFLAGS ""
#define BLD_BUILD_LDFLAGS ""
#define BLD_HOST_LDFLAGS ""
#define BLD_BUILD_LDXXFLAGS ""
#define BLD_HOST_LDXXFLAGS ""
#define BLD_BUILD_JFLAGS ""
#define BLD_HOST_JFLAGS ""
#define BLD_BUILD_ARCH ".a"
#define BLD_BUILD_EXE ""
#define BLD_BUILD_OBJ ".o"
#define BLD_BUILD_PIOBJ ".lo"
#define BLD_BUILD_CLASS ".class"
#define BLD_BUILD_SHLIB ".dylib"
#define BLD_BUILD_SHOBJ ".dylib"
#define BLD_HOST_ARCH ".a"
#define BLD_HOST_EXE ""
#define BLD_HOST_OBJ ".o"
#define BLD_HOST_PIOBJ ".lo"
#define BLD_HOST_CLASS ".class"
#define BLD_HOST_SHLIB ".dylib"
#define BLD_HOST_SHOBJ ".dylib"
#define BLD_TOOLS_DIR "${BLD_TOP}/tools"
#define BLD_BIN_DIR "${BLD_TOP}/bin"
#define BLD_LIB_DIR "${BLD_TOP}/lib"
#define BLD_INC_DIR "/usr/include/${BLD_PRODUCT}"
#define BLD_EXP_OBJ_DIR "${BLD_TOP}/obj"

#endif /* BLD_ALTERNATE_CONFIG */
