#
#   gitlab-ui.yml - Template CI/CD for building a UI hosted in S3
#
#   Inputs:
#       AWS_ACCOUNT     mobsense
#       PROFILE         dev, release, prod, ...
#       UI              "ui"
#   Outputs
#       build/ui/       rendered pages
#

stages:
    - build
    - publish

variables:
    ui: 'ui'

#cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#        - ${UI}/node_modules/

before_script:
    - ./configure --profile ${PROFILE}
    - npm link gulp
    - eval $(paks/assist/secrets --env '' --profile "${PROFILE}" --aws-profile "${AWS_ACCOUNT}" get)

build-ui:
    stage: build
    script:
        - ./paks/assist/build-parts --profile "${PROFILE}"
    artifacts:
        expire_in: 1 hour
        name: "rendered"
        paths:
            - ${UI}/build/
    tags: ['macosx']

publish-ui:
    stage: publish
    script:
        - ./paks/assist/publish-parts --profile "${PROFILE}"
    only: [ 'tags', 'triggers', 'schedules', 'web', 'api' ]
    except:
        variables:
            - $DEPLOY =~ /no-deploy/
    tags: ['macosx']
