#!/bin/bash

COUNT=$1
OUTPUT=$2

> $OUTPUT
while [ $COUNT -gt 0 ] ; 
do
    echo 0123456789012345678901234567890123456789012345678 >>$OUTPUT
    COUNT=$((COUNT - 1))
done
echo END OF DOCUMENT >>$OUTPUT

echo $OUTPUT is $(ls -lh $OUTPUT | awk '{print $5}')
